services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=20
#      - WATCHTOWER_MONITOR_ONLY=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    command: express-app
  express-app:
    image: bardys/express-app:latest
    ports:
      - 8080:8080
    container_name: express-app
    
  