name: sample

on: 
    push: 
        branches: 
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: push repo
              uses: actions/checkout@v4
            - name: set up docker buildx
              uses: docker/setup-buildx-action@v3
            - name: log in docker hub
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: build and push docker image
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/express-app:latest
